import scrollSmooth from "./modules/scrollSuave.js";
scrollSmooth();
import scrollAnimation from "./modules/animacaoScroll.js";
scrollAnimation();
import initNavTab from "./modules/navTab.js";
initNavTab();
import accordionFaq from "./modules/accordionFaq.js";
accordionFaq();
import modalLogin from "./modules/modalLogin.js";
modalLogin();
import initToolTip from "./modules/toolTip.js";
initToolTip();
import initMenuMobile from "./modules/menuMobile.js";
initMenuMobile();
import initAnimaNumeros from "./modules/anima-numeros.js";
initAnimaNumeros();
import initDataObject from "./modules/dataObject.js";
initDataObject();
/* import outsideClick from "./module/outsideClick.js";
outsideClick(); */
